[package]
authors = ["dskleingeld <11743287+dskleingeld@users.noreply.github.com>"]
edition = "2018"
readme = "README.md"
name = "server"
version = "0.1.0"

[features]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"

# embassy = { version = "0.1.0", path = "../embassy/embassy", features = ["defmt", "defmt-trace"] }
# embassy-traits = { version = "0.1.0", path = "../embassy/embassy-traits", features = ["defmt"] }
# embassy-nrf = { version = "0.1.0", path = "../embassy/embassy-nrf", features = ["defmt", "defmt-trace", "52832"] }

# defmt = "0.2.0"
# defmt-rtt = "0.2.0"

# cortex-m = { version = "0.7.2", features = ["inline-asm"] }
# cortex-m-rt = "0.6.13"
# cortex-m-semihosting = "0.3.3"
# embedded-hal    = { version = "0.2.4" }
# panic-probe = "0.2.0"
# futures = { version = "0.3.14", default-features = false, features = ["async-await"] }

# this lets you use `cargo fix`!
[[bin]]
name = "server"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
