[package]
authors = ["dskleingeld <11743287+dskleingeld@users.noreply.github.com>"]
edition = "2018"
readme = "README.md"
name = "server"
version = "0.1.0"

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
embassy = { version = "0.1.0", path = "../embassy/embassy", features = ["defmt", "defmt-trace"] }
embassy-traits = { version = "0.1.0", path = "../embassy/embassy-traits", features = ["defmt"] }
embassy-nrf = { version = "0.1.0", path = "../embassy/embassy-nrf", features = ["defmt", "defmt-trace", "52832"] }

defmt = "0.2.0"
defmt-rtt = "0.2.0"

cortex-m = { version = "0.7.1", features = ["inline-asm"] }
cortex-m-rt = "0.6.13"
embedded-hal    = { version = "0.2.4" }
panic-probe = "0.1.0"
futures = { version = "0.3.8", default-features = false, features = ["async-await"] }

[profile.release]
debug = true # default is `false`; using `true` is also OK
